# Generated by Django 3.2 on 2022-01-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_base_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountInfo',
        ),
        migrations.DeleteModel(
            name='BudgetInfo',
        ),
    ]
